In [13]:
import pandas as pd
import numpy as np
from scipy.cluster.hierarchy import linkage, dendrogram, cut_tree
import matplotlib.pyplot as plt

In [14]:
df = pd.read_csv("/kaggle/input/abc-csv/abc.csv")
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [15]:
df1 = df[['Fare', 'Age', 'PassengerId']]
df1.head()

Fare   Age  PassengerId
0   7.2500  22.0            1
1  71.2833  38.0            2
2   7.9250  26.0            3
3  53.1000  35.0            4
4   8.0500  35.0            5

In [16]:
df1.set_index("PassengerId", inplace=True)

In [17]:
df1.head()

Fare   Age
PassengerId               
1             7.2500  22.0
2            71.2833  38.0
3             7.9250  26.0
4            53.1000  35.0
5             8.0500  35.0

In [19]:
df1['Fare'].isnull().sum()

0

In [23]:
b = df1['Age'].mean()
s = round(b, 2)
s

29.7

In [24]:
df1['Age'].fillna(s, inplace=True)

/tmp/ipykernel_42/4067009316.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Age'].fillna(s, inplace=True)


In [25]:
df1['Age'].isnull().sum()

0

In [26]:
data = df1[['Fare', 'Age']]
data

Fare   Age
PassengerId               
1             7.2500  22.0
2            71.2833  38.0
3             7.9250  26.0
4            53.1000  35.0
5             8.0500  35.0
...              ...   ...
887          13.0000  27.0
888          30.0000  19.0
889          23.4500  29.7
890          30.0000  26.0
891           7.7500  32.0

[891 rows x 2 columns]

In [27]:
single_linkage = linkage(data, method='single')
single_linkage

array([[   0.        ,  212.        ,    0.        ,    2.        ],
       [ 320.        ,  891.        ,    0.        ,    3.        ],
       [ 376.        ,  892.        ,    0.        ,    4.        ],
       ...,
       [1776.        , 1777.        ,   21.53675968,   17.        ],
       [1775.        , 1778.        ,   46.51381787,  888.        ],
       [1408.        , 1779.        ,  249.57173312,  891.        ]])

In [29]:
complete_linkage = linkage(data, method='complete')
complete_linkage

array([[   0.        ,  212.        ,    0.        ,    2.        ],
       [ 628.        ,  870.        ,    0.        ,    2.        ],
       [   4.        ,  614.        ,    0.        ,    2.        ],
       ...,
       [1776.        , 1777.        ,  166.9042503 ,  871.        ],
       [1774.        , 1778.        ,  266.82203807,  888.        ],
       [1319.        , 1779.        ,  512.61116762,  891.        ]])

In [30]:
num_clusters = 10

In [31]:
cluster_assignments = cut_tree(single_linkage, n_clusters=num_clusters).flatten()
cluster_assignments

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 4, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 7, 0,

In [33]:
print("Cluster Assignments:")
for i, assignment in enumerate(cluster_assignments):
    print(f"Data point {i+1}: Cluster {assignment}")

Cluster Assignments:
Data point 1: Cluster 0
Data point 2: Cluster 0
Data point 3: Cluster 0
Data point 4: Cluster 0
Data point 5: Cluster 0
Data point 6: Cluster 0
Data point 7: Cluster 0
Data point 8: Cluster 0
Data point 9: Cluster 0
Data point 10: Cluster 0
Data point 11: Cluster 0
Data point 12: Cluster 0
Data point 13: Cluster 0
Data point 14: Cluster 0
Data point 15: Cluster 0
Data point 16: Cluster 0
Data point 17: Cluster 0
Data point 18: Cluster 0
Data point 19: Cluster 0
Data point 20: Cluster 0
Data point 21: Cluster 0
Data point 22: Cluster 0
Data point 23: Cluster 0
Data point 24: Cluster 0
Data point 25: Cluster 0
Data point 26: Cluster 0
Data point 27: Cluster 0
Data point 28: Cluster 1
Data point 29: Cluster 0
Data point 30: Cluster 0
Data point 31: Cluster 0
Data point 32: Cluster 2
Data point 33: Cluster 0
Data point 34: Cluster 0
Data point 35: Cluster 0
Data point 36: Cluster 0
Data point 37: Cluster 0
Data point 38: Cluster 0
Data point 39: Cluster 0
Data point 40